  name: CI
  on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: "3.11"
        - name: Install deps
          run: |
            python -m pip install --upgrade pip
            pip install -e . pytest build
        - name: Test
          run: pytest -q --maxfail=1 --disable-warnings -ra
        - name: Build wheel
          run: python -m build
  

